//USUARIOS
export const INICIAR_SESION_USUARIO_EXITO = "INICIAR_SESION_USUARIO_EXITO";
export const INICIAR_SESION_USUARIO_ERROR = "INICIAR_SESION_USUARIO_ERROR";
export const OBTENER_LISTA_USUARIOS_EXITO = "OBTENER_LISTA_USUARIOS_EXITO";
export const OBTENER_LISTA_USUARIOS_ERROR = "OBTENER_LISTA_USUARIOS_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const OBTENER_USUARIO_ERROR = "OBTENER_USUARIO_ERROR";
export const ENVIAR_EVALUACION = "ENVIAR_EVALUACION";
export const OBTENER_EVALUACIONES_EXITO = "OBTENER_EVALUACIONES_EXITO";

//ADMIN
export const INICIAR_SESION_ADMIN_EXITO = "INICIAR_SESION_ADMIN_EXITO";
export const INICIAR_SESION_ADMIN_ERROR = "INICIAR_SESION_ADMIN_ERROR";
export const OBTENER_ADMIN = "OBTENER_ADMIN";
export const OBTENER_ADMIN_ERROR = "OBTENER_ADMIN_ERROR";
export const OBTENER_CARRERAS_EXITO = "OBTENER_CARRERAS_EXITO";
export const OBTENER_CARRERAS_ERROR = "OBTENER_CARRERAS_ERROR";
export const OBTENER_CURSOS_EXITO = "OBTENER_CURSOS_EXITO";
export const OBTENER_CURSOS_ERROR = "OBTENER_CURSOS_ERROR";
export const CERRAR_SESION_ADMIN = "CERRAR_SESION_ADMIN";
export const OBTENER_EXCEL_ERROR = "OBTENER_EXCEL_ERROR";
export const OBTENER_EXCEL_EXITO = "OBTENER_EXCEL_EXITO";
export const AGREGAR_USUARIOS_ERROR = "AGREGAR_USUARIOS_ERROR";
export const AGREGAR_USUARIOS_EXITO = "AGREGAR_USUARIOS_EXITO";
export const AGREGAR_EVALUACION_EXITO = "AGREGAR_EVALUACION_EXITO";
export const OBTENER_ADMIN_EVALUACIONES_EXITO =
  "OBTENER_ADMIN_EVALUACIONES_EXITO";
export const OBTENER_ADMIN_CALIFICACIONES_EXITO =
  "OBTENER_ADMIN_CALIFICACIONES_EXITO";

//Alertas
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

//Cargando
export const CARGANDO = "CARGANDO";
